---
  # ansible-playbook playbook-t570.yml -i /etc/ansible/hosts

  name: Directory structure
  hosts: localhost
  gather_facts: no
  
  tasks:
  - file:
      path: /code
      state: directory
      mode: 0755
  - file:  
      path: /inbox
      state: directory
      mode: 0755
      # file:
      #   path: /repo
      #   state: directory
      #   mode: 0755
      # file:
      #   path: /sync
      #   state: directory
      #   mode: 0755
      # file:
      #   path: /temp
      #   state: directory
      #   mode: 0755
      # file:
      #   path: /tools
      #   state: directory
      #   mode: 0755
